### ISSUE TITLE
port to unix-like OSes

### ISSUE THREAD

**Issue by Domosed-gamin** [Horny-Milf-Near-You/NonGravitar#1]
Good project. I like description of the game in Readme file. Please make port to linux. You can use ncurses lib. This is good lib for cross platform development.

**Comment by its-hmny** [comment]
I'm slowly working on a [version 2.0](https://github.com/its-hmny/NonGravitar/tree/Version-2.0) of the game with more advanced features and Unix-like OSes support. This version is still very early, basic and not playable at the moment, but if you're interested you can compile and run it.
